### ISSUE TITLE
torus_levelset_nbm

### ISSUE THREAD

**Issue by ama103** [GPDEWinterSchool2016TAMU/3DSurfacePDEMatlab#25]
Hello!I am just reading the code you had written but I cannot understand how to get the right hand value .
res=s3p.*c3tp + ...
      ( 9*r^2*ct.*ct.*s3p.*c3tp ...
       -3*r^2*ct.*st.*s3p.*s3tp ...
      +18*r*R*ct.*s3p.*c3tp ...
       -3*r*R*st.*s3p.*s3tp ...
       +6*r^2*c3p.*s3tp ...
       +9*R^2*s3p.*c3tp ...
      +10*r^2*s3p.*c3tp ) ./(r^2*( r^2*ct.^2 ...
                                   +2*r*R*ct ...
                                   +R^2      ) );
I cannot understand how to get the formula. Please, help.Thank you very much!
（Well, I am not familiar with the format of issue, please forgive me if I had offended you. Thank you very much）

**Comment by lwy5515** [comment]
Hi @ama103, We use some software for symbolic computation (like maple or Mathematica) to get the right hand side data. I am not sure how we exactly got the formula above. But I created a Mathematica notebook attached here [lb-rhs.zip](https://github.com/GPDEWinterSchool2016TAMU/3DSurfacePDEMatlab/files/6571395/lb-rhs.zip) to show how I compute 
```
-\Delta_\gamma u
```
where `-\Delta_\gamma` is the Laplace-Beltrami operator and `u` is an analytic function.

**Comment by ama103** [comment]
@lwy5515, Ok, Thank you for your help!
